FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8
WORKDIR c:\web-app
COPY . .
SHELL ["powershell", "-command", "$ErrorActionPreference = 'Stop';"]
RUN New-WebApplication -Name 'app' -Site 'Default Web Site' -PhysicalPath c:\web-app


