# name: python-kube-manifest.yaml
# description: deploys application into sandbox namespace and exposes on an Azure internal load balancer
# author: Nigel Wardle
# created: 05/11/19
# modified 05/11/19 
# *******************************************

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: sixdegreesuk/python-standard:v1.0.0
        imagePullPolicy: Always
        resources: 
#          requests:
#            memory: "2000Mi"
#            cpu: "2000m"
#            limits:
#            memory: "2500Mi"
#            cpu: "2500m"
        ports:
        - containerPort: 5000
---
# expose pods to service on public IP
apiVersion: v1
kind: Service
metadata:
  name: python
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false" 
    # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "apps-subnet" # specify subnet
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: python
  sessionAffinity: ClientIP
