apiVersion: apps/v1
kind: Service
apiVersion: v1
metadata:
  name: python-standard-service1
  namespace: default
spec:
  selector:
    app: python-standard1
    type: front-end
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort
        