name: Docker Image Build PHP App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker image build /learn-to-containerise/docker-apps/linux/php --file Dockerfile --tag   node4demo/php-app:$(date +%s)
