# name: php-kube-manifest.yaml
# description: deploys application into sandbox namespace and exposes via a Kubernetes service
# author: Nigel Wardle
# created: 05/11/19
# modified 05/11/19 
# *******************************************
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: node4demo/nodejs
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
# expose pods to service on public IP
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false" 
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nodejs
